"""Auto-generated protocol dispatch table. Generated by scripts/generate_protocol.py. Do not edit by hand."""

import importlib
from pathlib import Path

from awf.authoring.workflow import DEFAULT_AUTHOR_PROFILE
from awf.paths import artifacts_dir

_HANDLER_PATHS = {
    "_handler_0": "awf.ops.run.op_run_start",
    "_handler_1": "awf.ops.run.op_run_status",
    "_handler_2": "awf.ops.run.op_run_list",
    "_handler_3": "awf.ops.run.op_run_resume",
    "_handler_4": "awf.ops.approval.op_approval_list",
    "_handler_5": "awf.ops.approval.op_approval_detail",
    "_handler_6": "awf.ops.approval.op_approval_approve",
    "_handler_7": "awf.ops.approval.op_approval_reject",
    "_handler_8": "awf.ops.approval.op_machine_action_preview",
    "_handler_9": "awf.ops.improvement.op_improvement_list",
    "_handler_10": "awf.ops.improvement.op_improvement_get",
    "_handler_11": "awf.ops.improvement.op_improvement_prepare",
    "_handler_12": "awf.ops.improvement.op_improvement_mark_ready",
    "_handler_13": "awf.ops.improvement.op_improvement_request_merge",
    "_handler_14": "awf.ops.improvement.op_improvement_merge",
    "_handler_15": "awf.ops.improvement.op_improvement_reject",
    "_handler_16": "awf.ops.artifact.op_artifact_list",
    "_handler_17": "awf.ops.artifact.op_artifact_read",
    "_handler_18": "awf.ops.registry.op_registry_list",
    "_handler_19": "awf.ops.registry.op_registry_get",
    "_handler_20": "awf.ops.registry.op_registry_validate",
    "_handler_21": "awf.ops.registry.op_registry_publish",
    "_handler_22": "awf.ops.registry.op_registry_reindex",
    "_handler_23": "awf.ops.registry.op_registry_retire",
    "_handler_24": "awf.ops.registry.op_registry_trust",
    "_handler_25": "awf.ops.registry.op_skill_invoke",
    "_handler_26": "awf.ops.authoring.op_workflow_author_draft",
    "_handler_27": "awf.ops.authoring.op_proposal_get",
    "_handler_28": "awf.ops.authoring.op_proposal_update",
    "_handler_29": "awf.ops.authoring.op_proposal_publish",
    "_handler_30": "awf.ops.authoring.op_proposal_reject",
    "_handler_31": "awf.ops.memory.op_memory_search",
    "_handler_32": "awf.ops.memory.op_memory_get",
    "_handler_33": "awf.ops.memory.op_memory_propose",
    "_handler_34": "awf.ops.memory.op_memory_publish",
    "_handler_35": "awf.ops.memory.op_memory_reject",
    "_handler_36": "awf.ops.memory.op_memory_block",
    "_handler_37": "awf.ops.memory.op_session_start",
    "_handler_38": "awf.ops.memory.op_session_append",
    "_handler_39": "awf.ops.memory.op_session_show",
    "_handler_40": "awf.ops.memory.op_session_summarize",
    "_handler_41": "awf.ops.voice.op_voice_session_start",
    "_handler_42": "awf.ops.voice.op_voice_session_event",
    "_handler_43": "awf.ops.voice.op_voice_session_close",
    "_handler_44": "awf.ops.voice.op_voice_submit_text",
    "_handler_45": "awf.ops.memory.op_episodic_search",
    "_handler_46": "awf.ops.memory.op_episodic_timeline",
    "_handler_47": "awf.ops.system.op_secret_set",
    "_handler_48": "awf.ops.system.op_secret_list_names",
    "_handler_49": "awf.ops.control.op_control_center_summary",
    "_handler_50": "awf.ops.control.op_control_center_run_detail",
    "_handler_51": "awf.ops.system.op_system_readiness",
    "_handler_52": "awf.ops.system.op_system_doctor",
    "_handler_53": "awf.ops.llm.op_llm_servers",
    "_handler_54": "awf.ops.llm.op_llm_models",
    "_handler_55": "awf.ops.llm.op_llm_serve",
    "_handler_56": "awf.ops.control.op_events_snapshot",
}


def _resolve_handler(alias):
    handler_path = _HANDLER_PATHS[alias]
    module_name, _, function_name = handler_path.rpartition(".")
    return getattr(importlib.import_module(module_name), function_name)


def _call_0(repo_root, conn, params):
    return _resolve_handler("_handler_0")(
        repo_root, conn, workflow_ref=params["workflow"], input_data=params.get("input", {})
    )


def _call_1(repo_root, conn, params):
    return _resolve_handler("_handler_1")(conn, run_id=params["runId"])


def _call_2(repo_root, conn, params):
    return _resolve_handler("_handler_2")(conn)


def _call_3(repo_root, conn, params):
    return _resolve_handler("_handler_3")(repo_root, conn)


def _call_4(repo_root, conn, params):
    return _resolve_handler("_handler_4")(conn)


def _call_5(repo_root, conn, params):
    return _resolve_handler("_handler_5")(conn, approval_id=params["approvalId"])


def _call_6(repo_root, conn, params):
    return _resolve_handler("_handler_6")(
        conn,
        approval_id=params["approvalId"],
        channel=params.get("channel", "manual"),
        risk_class=params.get("riskClass"),
    )


def _call_7(repo_root, conn, params):
    return _resolve_handler("_handler_7")(conn, approval_id=params["approvalId"], reason=params.get("reason", ""))


def _call_8(repo_root, conn, params):
    return _resolve_handler("_handler_8")(conn, approval_id=params["approvalId"])


def _call_9(repo_root, conn, params):
    return _resolve_handler("_handler_9")(conn, status=params.get("status"))


def _call_10(repo_root, conn, params):
    return _resolve_handler("_handler_10")(conn, improvement_id=params["improvementId"])


def _call_11(repo_root, conn, params):
    return _resolve_handler("_handler_11")(repo_root, conn, run_id=params["runId"], summary=params.get("summary"))


def _call_12(repo_root, conn, params):
    return _resolve_handler("_handler_12")(
        repo_root,
        conn,
        improvement_id=params["improvementId"],
        verdict_artifact_id=params["verdictArtifactId"],
        validation_artifact_ids=params.get("validationArtifactIds", []),
    )


def _call_13(repo_root, conn, params):
    return _resolve_handler("_handler_13")(repo_root, conn, improvement_id=params["improvementId"])


def _call_14(repo_root, conn, params):
    return _resolve_handler("_handler_14")(
        repo_root, conn, improvement_id=params["improvementId"], approval_id=params["approvalId"]
    )


def _call_15(repo_root, conn, params):
    return _resolve_handler("_handler_15")(
        repo_root, conn, improvement_id=params["improvementId"], reason=params.get("reason")
    )


def _call_16(repo_root, conn, params):
    return _resolve_handler("_handler_16")(conn, run_id=params["runId"])


def _call_17(repo_root, conn, params):
    return _resolve_handler("_handler_17")(
        conn, artifact_id=params["artifactId"], artifacts_root=artifacts_dir(repo_root)
    )


def _call_18(repo_root, conn, params):
    return _resolve_handler("_handler_18")(repo_root, kind=params["kind"], conn=conn)


def _call_19(repo_root, conn, params):
    return _resolve_handler("_handler_19")(
        repo_root, conn, kind=params["kind"], name=params["name"], version=params["version"]
    )


def _call_20(repo_root, conn, params):
    return _resolve_handler("_handler_20")(Path(params["path"]), kind=params.get("kind"))


def _call_21(repo_root, conn, params):
    return _resolve_handler("_handler_21")(repo_root, conn, path=Path(params["path"]), kind=params["kind"])


def _call_22(repo_root, conn, params):
    return _resolve_handler("_handler_22")(repo_root, conn)


def _call_23(repo_root, conn, params):
    return _resolve_handler("_handler_23")(conn, kind=params["kind"], name=params["name"], version=params["version"])


def _call_24(repo_root, conn, params):
    return _resolve_handler("_handler_24")(
        conn, kind=params["kind"], name=params["name"], version=params["version"], status=params["status"]
    )


def _call_25(repo_root, conn, params):
    return _resolve_handler("_handler_25")(
        repo_root,
        conn,
        ref=params["ref"],
        input_text=params["input"],
        profile_ref=params.get("profile", DEFAULT_AUTHOR_PROFILE),
    )


def _call_26(repo_root, conn, params):
    return _resolve_handler("_handler_26")(
        repo_root,
        conn,
        objective=params["objective"],
        name=params.get("name"),
        version=params.get("version"),
        profile_ref=params.get("profile", DEFAULT_AUTHOR_PROFILE),
    )


def _call_27(repo_root, conn, params):
    return _resolve_handler("_handler_27")(repo_root, conn, proposal_id=params["proposalId"])


def _call_28(repo_root, conn, params):
    return _resolve_handler("_handler_28")(
        repo_root, conn, proposal_id=params["proposalId"], content=params["content"], summary=params.get("summary")
    )


def _call_29(repo_root, conn, params):
    return _resolve_handler("_handler_29")(repo_root, conn, proposal_id=params["proposalId"], digest=params["digest"])


def _call_30(repo_root, conn, params):
    return _resolve_handler("_handler_30")(
        repo_root, conn, proposal_id=params["proposalId"], reason=params.get("reason")
    )


def _call_31(repo_root, conn, params):
    return _resolve_handler("_handler_31")(
        repo_root, conn, query=params["query"], profile_ref=params.get("profile", "default@1.0.0")
    )


def _call_32(repo_root, conn, params):
    return _resolve_handler("_handler_32")(repo_root, conn, ref=params["ref"])


def _call_33(repo_root, conn, params):
    return _resolve_handler("_handler_33")(repo_root, conn, path=Path(params["path"]), summary=params.get("summary"))


def _call_34(repo_root, conn, params):
    return _resolve_handler("_handler_34")(repo_root, conn, proposal_id=params["proposalId"], digest=params["digest"])


def _call_35(repo_root, conn, params):
    return _resolve_handler("_handler_35")(
        repo_root, conn, proposal_id=params["proposalId"], reason=params.get("reason")
    )


def _call_36(repo_root, conn, params):
    return _resolve_handler("_handler_36")(conn, ref=params["ref"])


def _call_37(repo_root, conn, params):
    return _resolve_handler("_handler_37")(conn, title=params.get("title"), expires_at=params.get("expiresAt"))


def _call_38(repo_root, conn, params):
    return _resolve_handler("_handler_38")(
        conn,
        session_id=params["sessionId"],
        role=params["role"],
        content=params["content"],
        summary=params.get("summary"),
    )


def _call_39(repo_root, conn, params):
    return _resolve_handler("_handler_39")(conn, session_id=params["sessionId"])


def _call_40(repo_root, conn, params):
    return _resolve_handler("_handler_40")(conn, session_id=params["sessionId"], summary=params.get("summary"))


def _call_41(repo_root, conn, params):
    return _resolve_handler("_handler_41")(
        conn, title=params.get("title"), wake_enabled=bool(params.get("wakeEnabled", False))
    )


def _call_42(repo_root, conn, params):
    return _resolve_handler("_handler_42")(
        conn,
        voice_session_id=params["voiceSessionId"],
        frame_type=params["frameType"],
        payload=params.get("payload", {}),
        turn_id=params.get("turnId"),
    )


def _call_43(repo_root, conn, params):
    return _resolve_handler("_handler_43")(conn, voice_session_id=params["voiceSessionId"], reason=params.get("reason"))


def _call_44(repo_root, conn, params):
    return _resolve_handler("_handler_44")(
        repo_root,
        conn,
        voice_session_id=params["voiceSessionId"],
        text=params["text"],
        workflow_ref=params.get("workflowRef"),
        voice_profile_ref=params.get("voiceProfileRef"),
        turn_id=params.get("turnId"),
    )


def _call_45(repo_root, conn, params):
    return _resolve_handler("_handler_45")(conn, query=params["query"], run_id=params.get("runId"))


def _call_46(repo_root, conn, params):
    return _resolve_handler("_handler_46")(conn, run_id=params["runId"])


def _call_47(repo_root, conn, params):
    return _resolve_handler("_handler_47")(repo_root, conn, name=params["name"], value=params["value"])


def _call_48(repo_root, conn, params):
    return _resolve_handler("_handler_48")(conn)


def _call_49(repo_root, conn, params):
    return _resolve_handler("_handler_49")(repo_root, conn)


def _call_50(repo_root, conn, params):
    return _resolve_handler("_handler_50")(repo_root, conn, run_id=params["runId"])


def _call_51(repo_root, conn, params):
    return _resolve_handler("_handler_51")(repo_root)


def _call_52(repo_root, conn, params):
    return _resolve_handler("_handler_52")(repo_root)


def _call_53(repo_root, conn, params):
    return _resolve_handler("_handler_53")(repo_root)


def _call_54(repo_root, conn, params):
    return _resolve_handler("_handler_54")(repo_root)


def _call_55(repo_root, conn, params):
    return _resolve_handler("_handler_55")(repo_root, conn, action="status")


def _call_56(repo_root, conn, params):
    return _resolve_handler("_handler_56")(conn, run_id=params.get("runId"), limit=int(params.get("limit", 100)))


METHOD_NAMES = (
    "awf/run.start",
    "awf/run.status",
    "awf/run.list",
    "awf/run.resume",
    "awf/approval.list",
    "awf/approval.detail",
    "awf/approval.approve",
    "awf/approval.reject",
    "awf/machine.actionPreview",
    "awf/improvement.list",
    "awf/improvement.get",
    "awf/improvement.prepare",
    "awf/improvement.markReady",
    "awf/improvement.requestMerge",
    "awf/improvement.merge",
    "awf/improvement.reject",
    "awf/artifact.list",
    "awf/artifact.read",
    "awf/registry.list",
    "awf/registry.get",
    "awf/registry.validate",
    "awf/registry.publish",
    "awf/registry.reindex",
    "awf/registry.retire",
    "awf/registry.trust",
    "awf/skill.invoke",
    "awf/workflow.authorDraft",
    "awf/proposal.get",
    "awf/proposal.update",
    "awf/proposal.publish",
    "awf/proposal.reject",
    "awf/memory.search",
    "awf/memory.get",
    "awf/memory.propose",
    "awf/memory.publish",
    "awf/memory.reject",
    "awf/memory.block",
    "awf/session.start",
    "awf/session.append",
    "awf/session.show",
    "awf/session.summarize",
    "awf/voice.sessionStart",
    "awf/voice.event",
    "awf/voice.sessionClose",
    "awf/voice.submitText",
    "awf/episodic.search",
    "awf/episodic.timeline",
    "awf/secret.set",
    "awf/secret.listNames",
    "awf/control.summary",
    "awf/control.runDetail",
    "awf/system.readiness",
    "awf/system.doctor",
    "awf/llm.servers",
    "awf/llm.models",
    "awf/llm.serveStatus",
    "awf/events.subscribe",
)

DISPATCH_TABLE = {
    "awf/run.start": _call_0,
    "awf/run.status": _call_1,
    "awf/run.list": _call_2,
    "awf/run.resume": _call_3,
    "awf/approval.list": _call_4,
    "awf/approval.detail": _call_5,
    "awf/approval.approve": _call_6,
    "awf/approval.reject": _call_7,
    "awf/machine.actionPreview": _call_8,
    "awf/improvement.list": _call_9,
    "awf/improvement.get": _call_10,
    "awf/improvement.prepare": _call_11,
    "awf/improvement.markReady": _call_12,
    "awf/improvement.requestMerge": _call_13,
    "awf/improvement.merge": _call_14,
    "awf/improvement.reject": _call_15,
    "awf/artifact.list": _call_16,
    "awf/artifact.read": _call_17,
    "awf/registry.list": _call_18,
    "awf/registry.get": _call_19,
    "awf/registry.validate": _call_20,
    "awf/registry.publish": _call_21,
    "awf/registry.reindex": _call_22,
    "awf/registry.retire": _call_23,
    "awf/registry.trust": _call_24,
    "awf/skill.invoke": _call_25,
    "awf/workflow.authorDraft": _call_26,
    "awf/proposal.get": _call_27,
    "awf/proposal.update": _call_28,
    "awf/proposal.publish": _call_29,
    "awf/proposal.reject": _call_30,
    "awf/memory.search": _call_31,
    "awf/memory.get": _call_32,
    "awf/memory.propose": _call_33,
    "awf/memory.publish": _call_34,
    "awf/memory.reject": _call_35,
    "awf/memory.block": _call_36,
    "awf/session.start": _call_37,
    "awf/session.append": _call_38,
    "awf/session.show": _call_39,
    "awf/session.summarize": _call_40,
    "awf/voice.sessionStart": _call_41,
    "awf/voice.event": _call_42,
    "awf/voice.sessionClose": _call_43,
    "awf/voice.submitText": _call_44,
    "awf/episodic.search": _call_45,
    "awf/episodic.timeline": _call_46,
    "awf/secret.set": _call_47,
    "awf/secret.listNames": _call_48,
    "awf/control.summary": _call_49,
    "awf/control.runDetail": _call_50,
    "awf/system.readiness": _call_51,
    "awf/system.doctor": _call_52,
    "awf/llm.servers": _call_53,
    "awf/llm.models": _call_54,
    "awf/llm.serveStatus": _call_55,
    "awf/events.subscribe": _call_56,
}
