"""Intent routing operations."""

from __future__ import annotations

import sqlite3
from pathlib import Path

from awf.cognition.router import (
    INTENT_ANSWER,
    INTENT_DRAFT_WORKFLOW,
    INTENT_PROPOSE_MEMORY,
    INTENT_RUN_WORKFLOW,
    classify_intent,
)
from awf.memory.sessions import append_entry
from awf.ops.authoring import op_workflow_author_draft
from awf.ops.run import DEFAULT_ASSISTANT_WORKFLOW_REF, op_run_start


def op_intent_classify(
    repo_root: Path,
    conn: sqlite3.Connection,
    *,
    text: str,
) -> dict:
    intent = classify_intent(repo_root, conn, text)
    return intent.to_dict()


def op_intent_dispatch(
    repo_root: Path,
    conn: sqlite3.Connection,
    *,
    text: str,
    voice_session_id: str | None = None,
    turn_id: str | None = None,
    async_execution: bool = False,
) -> dict:
    classified = classify_intent(repo_root, conn, text)
    intent_type = classified.intent

    if intent_type == INTENT_RUN_WORKFLOW:
        workflow_ref = classified.target_ref or "demo@1.0.0"
        payload_obj = classified.payload.get("objective", text)
        input_data = classified.payload.get("input_data") or {"objective": payload_obj}
        run_result = op_run_start(
            repo_root,
            conn,
            workflow_ref=workflow_ref,
            input_data=input_data,
            async_execution=async_execution,
        )
        run_id = run_result.get("run_id")
        return {
            "intent": INTENT_RUN_WORKFLOW,
            "classification": classified.to_dict(),
            "workflow_ref": workflow_ref,
            "run_id": run_id,
            "run_result": run_result,
            "response_text": f"Started workflow {workflow_ref} (run {run_id}).",
        }

    if intent_type == INTENT_DRAFT_WORKFLOW:
        objective = str(classified.payload.get("objective") or text)
        name = classified.payload.get("name")
        draft_result = op_workflow_author_draft(repo_root, conn, objective=objective, name=name)
        proposal_id = draft_result.get("proposal_id")
        return {
            "intent": INTENT_DRAFT_WORKFLOW,
            "classification": classified.to_dict(),
            "proposal_id": proposal_id,
            "draft_result": draft_result,
            "response_text": f"Created workflow draft proposal {proposal_id} for: {objective}",
        }

    if intent_type == INTENT_PROPOSE_MEMORY:
        fact = str(classified.payload.get("fact") or text)
        if voice_session_id:
            append_entry(conn, session_id=voice_session_id, role="operator", content={"fact": fact}, summary=fact)
        return {
            "intent": INTENT_PROPOSE_MEMORY,
            "classification": classified.to_dict(),
            "fact": fact,
            "response_text": f"Saved fact to memory: {fact}",
        }

    input_data = {"objective": text}
    if voice_session_id:
        input_data["voiceSessionId"] = voice_session_id
    if turn_id:
        input_data["turnId"] = turn_id

    run_result = op_run_start(
        repo_root,
        conn,
        workflow_ref=DEFAULT_ASSISTANT_WORKFLOW_REF,
        input_data=input_data,
        async_execution=async_execution,
    )
    run_id = run_result.get("run_id")
    response_text = ""
    outcome = run_result.get("outcome")
    if isinstance(outcome, dict):
        response_text = outcome.get("response_text", "")
    if not response_text:
        response_text = run_result.get("response_text", "")

    return {
        "intent": INTENT_ANSWER,
        "classification": classified.to_dict(),
        "workflow_ref": DEFAULT_ASSISTANT_WORKFLOW_REF,
        "run_id": run_id,
        "status": run_result.get("status", "RUNNING"),
        "run_result": run_result,
        "response_text": response_text or f"Response generated by {DEFAULT_ASSISTANT_WORKFLOW_REF} (run {run_id}).",
    }


__all__ = (
    "op_intent_classify",
    "op_intent_dispatch",
)
