function: wake
profile: windows-x64-cuda
files:
- acquisition: url
  url: https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/hey_jarvis_v0.1.onnx
  target_relative_path: hey_jarvis_v0.1.onnx
  sha256: 94a13cfe60075b132f6a472e7e462e8123ee70861bc3fb58434a73712ee0d2cb
- acquisition: url
  url: https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/melspectrogram.onnx
  target_relative_path: melspectrogram.onnx
  sha256: ba2b0e0f8b7b875369a2c89cb13360ff53bac436f2895cced9f479fa65eb176f
- acquisition: url
  url: https://github.com/dscripka/openWakeWord/releases/download/v0.5.1/embedding_model.onnx
  target_relative_path: embedding_model.onnx
  sha256: ba754db3cd768a524c655ea90655ee5e6055a43b8dfd29366a11e93716ae9e51
