"""Generate protocol mirrors from `awf.protocol.methods`.

Generated targets are complete files. This avoids region splicing in mixed
hand-written files.
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_SRC = REPO_ROOT / "backend" / "src"
PY_GENERATED = BACKEND_SRC / "awf" / "server" / "protocol_generated.py"
TS_GENERATED = REPO_ROOT / "frontend" / "shared" / "src" / "protocol.generated.ts"
GENERATOR_CACHE = BACKEND_SRC / "awf" / "server"

if str(BACKEND_SRC) not in sys.path:
    sys.path.insert(0, str(BACKEND_SRC))

from awf.protocol.methods import METHODS  # noqa: E402

HEADER = "Generated by scripts/generate_protocol.py. Do not edit by hand."


def _handler_alias(index: int) -> str:
    return f"_handler_{index}"


def _render_python() -> str:
    calls = []
    for index, method in enumerate(METHODS):
        calls.append(
            "\n".join(
                [
                    f"def _call_{index}(repo_root, conn, params):",
                    f'    return _resolve_handler("{_handler_alias(index)}")({method.python_args})',
                    "",
                ]
            )
        )

    table = ",\n".join(f'    "{method.name}": _call_{index}' for index, method in enumerate(METHODS))
    handlers = ",\n".join(f'    "{_handler_alias(index)}": "{method.handler}"' for index, method in enumerate(METHODS))
    names = ",\n".join(f'    "{method.name}"' for method in METHODS)
    return _format_python_content(
        f'"""Auto-generated protocol dispatch table. {HEADER}"""\n\n'
        "import importlib\n"
        "from pathlib import Path\n\n"
        "from awf.authoring.workflow import DEFAULT_AUTHOR_PROFILE\n"
        "from awf.paths import artifacts_dir\n"
        f"\n_HANDLER_PATHS = {{\n{handlers},\n}}\n\n"
        "def _resolve_handler(alias):\n"
        "    handler_path = _HANDLER_PATHS[alias]\n"
        '    module_name, _, function_name = handler_path.rpartition(".")\n'
        "    return getattr(importlib.import_module(module_name), function_name)\n\n"
        f"{chr(10).join(calls)}"
        f"METHOD_NAMES = (\n{names},\n)\n\n"
        f"DISPATCH_TABLE = {{\n{table},\n}}\n"
    )


def _format_python_content(content: str) -> str:
    GENERATOR_CACHE.mkdir(parents=True, exist_ok=True)
    temp_path = GENERATOR_CACHE / "__protocol_generated_format_tmp.py"
    temp_path.write_text(content, encoding="utf-8")
    try:
        subprocess.run(
            [sys.executable, "-m", "ruff", "format", str(temp_path)],
            cwd=REPO_ROOT,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return temp_path.read_text(encoding="utf-8")
    finally:
        temp_path.unlink(missing_ok=True)


def _render_typescript() -> str:
    names = "\n".join(f'  | "{method.name}"' for method in METHODS)
    methods = "\n\n  ".join(method.ts_method for method in METHODS)
    return (
        f"// {HEADER}\n\n"
        "import type {\n"
        "  Approval,\n"
        "  ApprovalApproveOptions,\n"
        "  ApprovalDetail,\n"
        "  Artifact,\n"
        "  ControlRunDetail,\n"
        "  ControlSummary,\n"
        "  EventsSnapshot,\n"
        "  ImprovementProposal,\n"
        "  LlmModelsReport,\n"
        "  LlmServeStatus,\n"
        "  LlmServersReport,\n"
        "  MachineActionPreview,\n"
        "  MemorySearchResult,\n"
        "  Proposal,\n"
        "  RegistryEntry,\n"
        "  RunStartResult,\n"
        "  RunStatus,\n"
        "  RunSummary,\n"
        "  SystemDoctor,\n"
        "  SystemReadiness,\n"
        "  VoiceFrameType,\n"
        "  VoiceSessionResult,\n"
        "  VoiceSubmitTextResult,\n"
        '} from "./types.js";\n\n'
        "export type MethodName =\n"
        f"{names};\n\n"
        "export abstract class ProtocolGeneratedClient {\n"
        "  protected abstract runCallTimeoutMs: number;\n"
        "  protected abstract callTimeoutMs: number;\n"
        "  protected abstract call<T>(method: MethodName, params?: Record<string, unknown>, timeoutMs?: number): Promise<T>;\n\n"
        f"  {methods}\n"
        "}\n"
    )


def _diff(path: Path, expected: str) -> str:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return ""
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def check_generated() -> int:
    failures = []
    for path, expected in ((PY_GENERATED, _render_python()), (TS_GENERATED, _render_typescript())):
        diff = _diff(path, expected)
        if diff:
            failures.append(diff)
    if failures:
        print("protocol generated files are stale; run `python scripts/generate_protocol.py --write`")
        print("\n".join(failures))
        return 1
    return 0


def write_generated() -> int:
    _write(PY_GENERATED, _render_python())
    _write(TS_GENERATED, _render_typescript())
    return 0


def _subparser_choices(action: argparse._SubParsersAction) -> dict[str, argparse.ArgumentParser]:
    return action.choices


def _child_subparsers(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _parser_has_path(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> bool:
    return _parser_for_path(parser, path) is not None


def _parser_for_path(parser: argparse.ArgumentParser, path: tuple[str, ...]) -> argparse.ArgumentParser | None:
    current = parser
    for part in path:
        subparsers = _child_subparsers(current)
        if subparsers is None:
            return None
        choices = _subparser_choices(subparsers)
        if part not in choices:
            return None
        current = choices[part]
    return current


def _action_kind(action: argparse.Action) -> str:
    if isinstance(action, argparse._StoreTrueAction):
        return "store_true"
    if isinstance(action, argparse._AppendAction):
        return "append"
    return "store"


def _normalize_nargs(value):
    if value == 0:
        return None
    return "REMAINDER" if value == argparse.REMAINDER else value


def _actual_arguments(parser: argparse.ArgumentParser) -> list[dict]:
    actions = [
        action
        for action in parser._actions
        if not isinstance(action, (argparse._HelpAction, argparse._SubParsersAction))
    ]
    return [
        {
            "flags": tuple(action.option_strings) if action.option_strings else (action.dest,),
            "action": _action_kind(action),
            "required": bool(getattr(action, "required", False)),
            "default": action.default,
            "choices": tuple(action.choices) if action.choices is not None else None,
            "nargs": _normalize_nargs(action.nargs),
        }
        for action in actions
    ]


def _expected_arguments(spec: dict) -> list[dict]:
    expected = []
    for arg in spec.get("args", ()):
        action = arg.get("action", "store")
        default = arg.get("default")
        if action == "store_true" and "default" not in arg:
            default = False
        flags = tuple(arg["flags"])
        nargs = _normalize_nargs(arg.get("nargs"))
        positional = all(not flag.startswith("-") for flag in flags)
        required = positional and nargs != "REMAINDER"
        expected.append(
            {
                "flags": flags,
                "action": action,
                "required": bool(arg.get("required", required)),
                "default": default,
                "choices": tuple(arg["choices"]) if "choices" in arg else None,
                "nargs": nargs,
            }
        )
    return expected


def check_argparse_parity() -> int:
    cli_main = importlib.import_module("awf.cli.main")
    parser = cli_main.build_parser()
    errors = []
    cli_specs = {spec["path"]: spec for spec in cli_main.CLI_COMMAND_SPECS}
    for method in METHODS:
        if method.cli_path and method.cli_path not in cli_specs:
            errors.append(f"missing CLI metadata for {method.name}: {' '.join(method.cli_path)}")
    for path, spec in cli_specs.items():
        command_parser = _parser_for_path(parser, path)
        if command_parser is None:
            errors.append(f"missing CLI parser path: {' '.join(path)}")
            continue
        actual = _actual_arguments(command_parser)
        expected = _expected_arguments(spec)
        if actual != expected:
            errors.append(f"CLI argument drift for {' '.join(path)}: expected {expected!r}, got {actual!r}")
    if errors:
        print("\n".join(errors))
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check AWF protocol mirrors")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check-argparse", action="store_true")
    args = parser.parse_args(argv)
    if args.write:
        return write_generated()
    if args.check_argparse:
        return check_argparse_parity()
    return check_generated()


if __name__ == "__main__":
    sys.exit(main())
